version: '2'
services:
  sip.orchestrator1:
    image: ibmcom/voice-gateway-so:beta.latest
#    image: bpulito/ibm-cognitive-gw:cso.0.2.3
    container_name: voice-gateway-so1
    ports:
      - "5060:5060"
      - "5060:5060/udp"
    environment:
      # Host name of the CMR.
      - RTP_RELAY_HOST=media.relay:8080
      - SIP_HOST=${EXTERNAL_IP}
      - SIP_PORT=5060

      # Uncomment and specify when the Conversation API is used
      - CONV_USERNAME=968579a4-d9ed-46b3-8492-e9a9bf555021
      - CONV_PASSWORD=InWtiUpYhF1Z
      - CONV_ENDPOINT=https://gateway.watsonplatform.net/conversation/api
      - CONV_WORKSPACE_ID=abc1abf0-4025-4a25-a8c6-ac283b4b7463

      # Logging related variables
      - ENABLE_TRANSCRIPTION_AUDIT_MESSAGES=true
      - LOG_LEVEL=finest
      - NUMCONV_PLUGIN_ENABLE=true

  sip.orchestrator2:
    image: ibmcom/voice-gateway-so:beta.latest
#    image: bpulito/ibm-cognitive-gw:cso.0.2.3
    container_name: voice-gateway-so2
    ports:
      - "5064:5064"
      - "5064:5064/udp"
    environment:
      # Host name of the CMR.
      - RTP_RELAY_HOST=media.relay:8080
      - SIP_HOST=${EXTERNAL_IP}
      - SIP_PORT=5064

      # Uncomment and specify when the Conversation API is used
      - CONV_USERNAME=968579a4-d9ed-46b3-8492-e9a9bf555021
      - CONV_PASSWORD=InWtiUpYhF1Z
      - CONV_ENDPOINT=https://gateway.watsonplatform.net/conversation/api
      - CONV_WORKSPACE_ID=abc1abf0-4025-4a25-a8c6-ac283b4b7463

      # Logging related variables
      - ENABLE_TRANSCRIPTION_AUDIT_MESSAGES=true
      - LOG_LEVEL=finest
      - NUMCONV_PLUGIN_ENABLE=true

  omni.sip.lb:
    image: omni-sip-lb:0.0.1
    container_name: omni-sip-lb
    ports:
      - "5068:5068"
      - "5068:5068/udp"
    environment:
      # Configuration to run the Omni Call Switch
      - OCS_SIP_LOAD_BALANCER_SERVER_URI_LIST=sip:${EXTERNAL_IP}:5060,sip:${EXTERNAL_IP}:5064

      # SIP specific configuration
      - SIP_HOST=${EXTERNAL_IP}
      - SIP_UDP_PORT=5068
      - SIP_TCP_PORT=5068

      - LOG_LEVEL=fine

  media.relay:
    image: ibmcom/voice-gateway-mr:beta.latest
#    image: bpulito/ibm-cognitive-gw:cmr.0.2.5
    container_name: voice-gateway-mr
    ports:
      - "16384-16394:16384-16394/udp"
    environment:
      - WATSON_RELAY_SDP_ADDRESS=${EXTERNAL_IP}
      - RTP_UDP_PORT_RANGE=16384-16394
      - RTP_RELAY_LOGLEVEL=DEBUG
      - RTP_PORT=8080

      # Creds for Bluemix STT
      - WATSON_STT_USER=3b36c01c-6dfb-4cb6-9a7f-ea4fafd1b2f1
      - WATSON_STT_PASSWORD=pPI1h4hcgExG
      - WATSON_STT_ENDPOINT=https://stream.watsonplatform.net/speech-to-text/api

      # Creds for Bluemix TTS
      - WATSON_TTS_USER=e48b9a83-98e2-4499-8db0-e09b2d8f2629
      - WATSON_TTS_PASSWORD=wIHJktWDn3Jp
      - WATSON_TTS_VOICE=en-US_MichaelVoice
      - WATSON_TTS_ENDPOINT=https://stream.watsonplatform.net/text-to-speech/api

      - RTP_RELAY_LOGLEVEL=TRACE
      
#  apache.httpd:
#    image: httpd
#    ports:
#      - "443:443"
#    environment:
#      - SSL_VERSION_LIBRARY=OpenSSL/1.0.1
#    volumes:
#      - $PWD:/usr/local/apache2/conf

