version: '2'
services:
  media.relay:
    image: ibmcom/voice-gateway-mr:beta.latest
#    image: bpulito/ibm-cognitive-gw:cmr.0.2.5
    container_name: voice-gateway-mr
    ports:
      - "16384-16394:16384-16394/udp"
      - "8090:8090"
    environment:
      - WATSON_RELAY_SDP_ADDRESS=${EXTERNAL_IP}
      - RTP_UDP_PORT_RANGE=16384-16394
      - RTP_RELAY_LOGLEVEL=DEBUG
      - RTP_PORT=8090

      # Creds for Bluemix STT
      - WATSON_STT_USER=3b36c01c-6dfb-4cb6-9a7f-ea4fafd1b2f1
      - WATSON_STT_PASSWORD=pPI1h4hcgExG
      - WATSON_STT_ENDPOINT=https://stream.watsonplatform.net/speech-to-text/api

      # Creds for Bluemix TTS
      - WATSON_TTS_USER=e48b9a83-98e2-4499-8db0-e09b2d8f2629
      - WATSON_TTS_PASSWORD=wIHJktWDn3Jp
      - WATSON_TTS_VOICE=en-US_MichaelVoice
      - WATSON_TTS_ENDPOINT=https://stream.watsonplatform.net/text-to-speech/api

      - RTP_RELAY_LOGLEVEL=TRACE
      
#  apache.httpd:
#    image: httpd
#    ports:
#      - "443:443"
#    environment:
#      - SSL_VERSION_LIBRARY=OpenSSL/1.0.1
#    volumes:
#      - $PWD:/usr/local/apache2/conf

