version: '2'
services:
  sip.orchestrator:
    image: ibmcom/voice-gateway-so:beta.latest
    ports:
      - "5060:5060"
      - "5060:5060/udp"
    environment:
      # Host name of the CMR.
      - RTP_RELAY_HOST=media.relay:8080
      - SIP_HOST=${EXTERNAL_IP}
      - SIP_PORT=5060

      # Uncomment and specify when the Conversation API is used
      - CONV_WORKSPACE_ID=
      - CONV_USERNAME=
      - CONV_PASSWORD=
      - CONV_ENDPOINT=https://gateway.watsonplatform.net/conversation/api

      # Name of the Watson dialog or conversation being orchestrated
      #- DIALOG_NAME=
      #- DIALOG_USERNAME=
      #- DIALOG_PASSWORD=
      #- DIALOG_ENDPOINT=

      # Set to true to enable the MQTT transcription plugin
      - MQTT_PLUGIN_ENABLE=false

      # Uncomment to turn off audit messages. Default is true
      - ENABLE_AUDIT_MESSAGES=true
      - ENABLE_TRANSCRIPTION_AUDIT_MESSAGES=true

      # Uncomment to change the threshold for reporting latency thresholds. Default is 20ms (uncommenting and setting will log for all transactions.)
      # - LATENCY_REPORTING_THRESHOLD=0
      # Uncomment to change the threshold for reporting relay latency thresholds. Default is 1000ms (uncommenting and setting will log for all transactions.)
      # - RELAY_LATENCY_REPORTING_THRESHOLD=0

      - LOG_LEVEL=fine

  media.relay:
    #image: bpulito/ibm-cognitive-gw:cmr.latest
    image: ibmcom/voice-gateway-mr:beta.latest
    ports:
      - "16384-16394:16384-16394/udp"
    environment:
      - WATSON_RELAY_SDP_ADDRESS=${EXTERNAL_IP}
      - RTP_UDP_PORT_RANGE=16384-16394
      - RTP_RELAY_LOGLEVEL=DEBUG
      - RTP_RELAY_RECORD=false
      - RTP_PORT=8080

      # Creds for Bluemix STT
      - WATSON_STT_USER=
      - WATSON_STT_PASSWORD=
      #- WATSON_STT_MODEL=
      #- WATSON_STT_EXTRAS=cluster=secretcustb2
      #- WATSON_STT_ENDPOINT=https://stream.watsonplatform.net/speech-to-text/api
      #- WATSON_AUTH_URL=https://stream.watsonplatform.net/speech-to-text/api

      # Creds for Bluemix TTS
      - WATSON_TTS_USER=
      - WATSON_TTS_PASSWORD=
      #- WATSON_TTS_VOICE=en-US_MichaelVoice
      #- WATSON_TTS_ENDPOINT=https://stream.watsonplatform.net/text-to-speech/api

      - RTP_RELAY_LOGLEVEL=TRACE
#    volumes:
#      - $PWD/recordings:/cgw-media-relay/recordings
