version: '2'
services:
  sip.orchestrator:
    image: icr.io/voice-gateway/sip-orchestrator:latest
    container_name: voice-gateway-so
    ports:
      - "5060:5060"
      - "5060:5060/udp"
      - "9443:9443"
      - "9080:9080"
    environment:
      # Host name of the CMR.
      - MEDIA_RELAY_HOST=media.relay:8080
      - SIP_HOST=${EXTERNAL_IP}

      # Uncomment and specify when the Conversation API is used
      - WATSON_CONVERSATION_WORKSPACE_ID=
      - WATSON_CONVERSATION_USERNAME=
      - WATSON_CONVERSATION_PASSWORD=
      - WATSON_CONVERSATION_URL=

      # Logging related variables
      - ENABLE_TRANSCRIPTION_AUDIT_MESSAGES=true
      - LOG_LEVEL=finest
	  
      # Uncomment SMS Integration related variables when required  
      #- WEB_HOOK_HOST=
      #- SMS_GW_URL=
      #- SMS_GW_USERNAME=
      #- SMS_GW_PASSWORD=
      #- TENANT_PHONE_NUMBER=
      #- ENABLE_INBOUND_SMS=false
      #- HTTP_HOST=*
      #- SMS_GW_READ_TIMEOUT=
      #- HTTPS_PORT=
      #- HTTP_PORT=

  media.relay:
    image: icr.io/voice-gateway/media-relay:latest
    container_name: voice-gateway-mr
    ports:
      - "16384-16394:16384-16394/udp"
    environment:
      - SDP_ADDRESS=${EXTERNAL_IP}
      - RTP_UDP_PORT_RANGE=16384-16394
      - MEDIA_RELAY_LOG_LEVEL=DEBUG
      - MEDIA_RELAY_WS_PORT=8080

      # Creds for Bluemix STT
      - WATSON_STT_USERNAME=
      - WATSON_STT_PASSWORD=
      - WATSON_STT_URL=

      # Creds for Bluemix TTS
      - WATSON_TTS_USERNAME=
      - WATSON_TTS_PASSWORD=
      - WATSON_TTS_URL=
      - WATSON_TTS_VOICE=en-US_MichaelVoice

      # Uncomment the following three lines to enable call recording
      #- ENABLE_RECORDING=true
    #volumes:
      #- $PWD/recordings:/vgw-media-relay/recordings
